# The URL the site will be built for
base_url = "https://blog.dziban.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true

theme = "no-style-please"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-atelierdune-light"

[extra]
# Put all your custom variables here
list_pages = true

author = "Marce Coll"
logo = "images/logo.png"
header_nav = [
  { name = "~home", url = "/" },
  { name = "(exp prog)", url = "/exploratory-programming" },
  { name = "*essays", url = "/essays/" },
  { name = "@posts", url = "/posts/" },
]

add_toc = true